<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Services\Buildings\DTOs\" />
    <Folder Include="Services\Clients\DTOs\" />
    <Folder Include="Services\Geography\DTOs\" />
  </ItemGroup>
</Project>
